
## EMG Preprocessing values
SENSOR_FREQ = 2000
PROCESSING_FREQ = 33.3
RESTRICTED_SIGNAL_GAIN = 120
FILTER_LOW_CUTOFF_FREQUENCY = None
FILTER_HIGH_CUTOFF_FREQUENCY = 10
FILTER_ORDER = 4
FILTER_BTYPE = 'low'
HAND_DEADBAND_TRESHOLD = 0.7
WRIST_DEADBAND_TRESHOLD = 0.7
HAND_GAIN = 1,3
WRIST_GAIN = 1,3

## Sekvensiell styring (del 3)
HYSTERESIS_THRESHOLD = 3
HYSTERESIS_WIDTH = 1

